### ISSUE TITLE
Render MCCI huds without using the font renderer

### ISSUE THREAD

**Issue by willocn** [Noxcrew/noxesium#3]
It would be nice if this mod rendered the MCCI huds/tablist properly rather than using the font kludge, since it seems to have extremely poor performance.

**Comment by Aeltumn** [comment]
I plan on looking into improving the UI rendering on the server-side so it improves for everyone. If you specifically want client-side fps improvements you should look into installing Exordium which improves UI fps in a very nice maintainable way.

**Comment by Aeltumn** [comment]
Going to close this for now after I've done more thinking about how to approach optimizing UI on MCCI. The problem we run into is that Minecraft's font rendering is simply very badly optimized, but in a way where the whole system is fundamentally unoptimized, not in a way where a small part of it can be optimized. So, the only kinds of optimization Noxesium could do would be to either re-implement the entire scoreboard/bossbar rendering code which would break compatibility with many other mods, or do all rendering fully custom which would be tons of effort for a small amount of users.

I think re-implementing the entire scoreboard/bossbar is the more feasible option, but it's still a lot of work and would be a very complex and longterm project. So since this is not easily solvable and it would be a very longterm project that goes beyond the scope of this issue.
