### ISSUE TITLE
Incompatibility with Feather Client and experimental UI improvements

### ISSUE THREAD

**Issue by OmegaPhoenix637** [Noxcrew/noxesium#39]
turning on experimental features will remove the featherclient overlay and turn off all feather client features with the bosbar and scoreboard, like changing the scale

**Comment by Aeltumn** [comment]
The experimental UI changes are currently not compatible with any 3rd party UI additions because it fully rewrites the entire UI. I'll consider making them unusable when specifically using Feather as I can't support their rescaling regardless. I do want to support minor 3rd party additions at some point.
