### ISSUE TITLE
[1.20.4]: Breaks Mod hud rendering

### ISSUE THREAD

**Issue by mysticdrew** [Noxcrew/noxesium#63]
Hey there, JourneyMap dev here. 
I've had a user report to me that having - noxesium 1.2.2 1.20.4  installed prevented the Minimap and another mod's hud elements from rendering.

**Comment by Aeltumn** [comment]
Ah yeah, that's intentional on the 1.20.4 version. It's because they are using some experimental UI optimizations. They have to specifically turn them on in the settings menu and there's a very big warning explicitly saying it will break 3rd party mods. They shouldn't have reported that as a bug to you it was a user error.

The 1.20.5 version of Noxesium no longer breaks 3rd party mods entirely, so it shouldn't happen there anymore.

**Comment by mysticdrew** [comment]
Ahh sounds good, thanks.
